connector:
  port: ${cport}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://local/message
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: local:8848
        ip: ${sip:127.0.0.1}
  application:
    name: connector-service
  redis:
    host: local
server:
  port: ${sport}
management:
  endpoints:
    web:
      exposure:
        include: "*"