spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: root
    password: test