server:
  port: 1666
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://local/message
    username: root
    password: root
  rabbitmq:
    addresses: local
    username: message
    password: message
    virtual-host: /
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 10
    publisher-confirm-type: correlated
